name: monteclora
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - ca-certificates=2024.12.31
  - intel-openmp=2023.1.0
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ncurses=6.4
  - openssl=3.0.15
  - pip=25.0
  - python=3.9.21
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - accelerate==1.3.0
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.12
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - async-timeout==5.0.1
      - attrs==25.1.0
      - calflops==0.3.2
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - contourpy==1.3.0
      - cycler==0.12.1
      - datasets==3.3.0
      - deepspeed==0.16.4
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - eval-type-backport==0.2.2
      - evaluate==0.4.3
      - filelock==3.17.0
      - fire==0.7.0
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grpcio==1.70.0
      - hjson==3.1.0
      - huggingface-hub==0.28.1
      - idna==3.10
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - jinja2==3.1.5
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - loralib==0.1.2
      - markdown==3.7
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - networkx==3.2.1
      - ninja==1.11.1.3
      - nltk==3.9.1
      - numpy==2.0.2
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu11==8.7.0.84
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu11==2.19.3
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.4.127
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.0.0
      - platformdirs==4.3.6
      - propcache==0.2.1
      - protobuf==5.29.3
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==19.0.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyinstrument==5.0.1
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - rouge-score==0.1.2
      - safetensors==0.5.2
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - sentencepiece==0.2.0
      - sentry-sdk==2.21.0
      - setproctitle==1.3.4
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tokenizers==0.20.3
      - torch==2.6.0+cu124
      - torchaudio==2.2.1+cu118
      - torchvision==0.21.0+cu124
      - tqdm==4.67.1
      - triton==3.2.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - wandb==0.19.6
      - werkzeug==3.1.3
      - xxhash==3.5.0
      - yarl==1.18.3
      - zipp==3.21.0
